@startuml

object regulations{
    list_of_nations
}

object nation_regulation

object document_regulation

object vaccination_regulation

object criminal_regulation

regulations --> nation_regulation
regulations --> document_regulation
regulations --> vaccination_regulation
regulations --> criminal_regulation

class Bulletin{
    regulations_raw
    date
}


class Inspector{
    bulletins
    regulations: dict
    receive_bulletins()
    inspect(entrant)    
}

Inspector --> regulations
Inspector --> Bulletin

abstract Entrant{
    passport
    certificate_of_vaccination
}

Inspector --> Entrant

class ArstotzkaCitizenEntrant{
    id_card
}

class ForeignerEntrant{
    access_permit
    work_pass
    grant_of_asylum
    diplomatic_authorization
}

Entrant <|-- ForeignerEntrant
Entrant <|-- ArstotzkaCitizenEntrant

@enduml