@startuml

class Cidadão{
    papeis
}

class Boletim{
    descrição
    data
}

class Inspetor{
    regras: list[Regra]
    recebe_boletim(boletim_ministerial: str)
    inspecionar(entrante: str)
}

abstract Regra{
    executa(boletim: Boletim)
}

abstract RegraNação{
    países
}

class RegraPassaporte{
    ID
    executa()
}

class RegraCriminal{
    nome_procurado
    executa()
}

class RegraVacinal{
    vacinas
    executa()
}

class RegraEstrangeiro{
    garantia de asilo *
    autorização diplomática *
    permisão de acesso
    visto de trabalho
    propósito do trabalho
    executa()
}

class RegraNatural{
    ID_card
    executa()
}

abstract Papel{
    raw: str
}

class Passaporte{
    __call__()
}

class CertificadoVacinação{
    __call__()
}

class IDCard{
    __call__()
}

class PermissãoAcesso{
    __call__()
}

class PermissãoTrabalho{
    __call__()
}

class GarantiaAsilo{
    __call__()
}    

class AutorizaçãoDiplomática{
    __call__()
}


Papel <|- Passaporte
Papel <|--- CertificadoVacinação
Papel <|-- IDCard
Papel <|--- PermissãoAcesso
Papel <|-- PermissãoTrabalho
Papel <|--- GarantiaAsilo
Papel <|-- AutorizaçãoDiplomática

Cidadão --> Papel

Regra <|-- RegraNação
Regra <|--- RegraCriminal
Regra <|--- RegraPassaporte
Regra <|--- RegraVacinal
RegraNação <|-- RegraNatural
RegraNação <|-- RegraEstrangeiro

Inspetor ---> Regra
Inspetor --> Boletim
Inspetor --> Cidadão


@enduml