@startuml

abstract Cidadão{
    nome
    nacionalidade

    passaporte
    carteira_vacinação
}

class CidadãoNatural{
    ID_card
}

class CidadãoEstrangeiro{
    garantia_de_asilo
    autorização_diplomática
    permissão_de_acesso
    visto_de_rabalho
}

class Passaporte{
    identificador
    validade
}

object Boletim

class Inspetor{
    cidadão
    boletim
    regras
    inspeção
    recebe_boletim()
    carrega_regras(boletim)
    inspecionar(cidadão)
    processa(cidadão, regra)

}

abstract Regra{    
    países
    executa(cidadão: Cidadão)
}


class RegraPassaporte{
    ID
    executa()
}
class RegraCriminal{
    nome_procurado
    executa()
}
class RegraVacinal{
    vacinas
    executa()
}
class RegraEstrangeiro{
    garantia de asilo *
    autorização diplomática *
    permisão de acesso
    visto de trabalho
    propósito do trabalho
    executa()
}
class RegraNatural{
    ID_card
    executa()
}

class CarteiraVacinação{
    vacinas
}

Cidadão <|-- CidadãoEstrangeiro
Cidadão <|-- CidadãoNatural

Regra ..> Cidadão

Regra <|--- RegraPassaporte
Regra <|--- RegraCriminal
Regra <|--- RegraVacinal
Regra <|--- RegraEstrangeiro
Regra <|--- RegraNatural

Regra <- Inspetor

Inspetor -> Boletim
Inspetor --> Cidadão

Inspetor .> RegraPassaporte
Inspetor .> RegraCriminal
Inspetor .> RegraVacinal
Inspetor .> RegraEstrangeiro
Inspetor .> RegraNatural

Cidadão --> Passaporte
Cidadão --> CarteiraVacinação


@enduml