@startuml

Inspetor -> recebe_boletim: boletim
recebe_boletim --> carrega_regras: boletim 
carrega_regras --> Inspetor: regras
recebe_boletim -> Inspetor: 
Inspetor -> inspeciona: Cidadão
inspeciona -> processa_regras: Cidadão, regras
processa_regras --> processa_regras: Cidadão, regra
processa_regras --> inspeciona
inspeciona -> Inspetor: saída

@enduml